### ISSUE TITLE
Netlify Deployment don't works

### ISSUE THREAD

**Issue by MattixNow** [marinaaisa/nuxt-markdown-blog-starter#3]
https://brave-borg-57a14b.netlify.com/

![image](https://user-images.githubusercontent.com/32040951/60036461-92550780-96af-11e9-9271-1acec74a5307.png)

**Comment by cesargb** [comment]
Hi @MattixNow,

For deploy in netlify, you need this configuration:

* Branch to deploy: master, or which-ever branch you prefer
* Build command: npm run generate
* Publish directory: dist

see, https://nuxtjs.org/faq/netlify-deployment/

**Comment by MattixNow** [comment]
Thanks

**Comment by marinaaisa** [comment]
Thank you @cesargb for the fast reply :)
